### ISSUE TITLE
Add WALRUS: Walrus DAO

### ISSUE THREAD

**Issue by WalrusDAO** [spectrum-finance/default-token-list#18]
- [x] I understand that token listing is not required to use the ErgoDEX Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the ErgoDEX default token list.
- [x] I will not ping the ErgoDEX team about this listing request.

**Please provide the following information for your token.**

Network:  
Project Name:  
Link to explorer:  
URI to token's logo:  
Token Name:  
Token Decimals:  

Link to the official homepage of project/token:  
Links to the official socials of project/token:  
Link to CoinMarketCap or CoinGecko page of project/token (if exists):

**Comment by yasha-black** [comment]
@WalrusDAO you didn't fill out the form. Please provide the following information:

Network:
Project Name:
Link to explorer:
URI to token's logo:
Token Name:
Token Decimals:

Link to the official homepage of project/token:
Links to the official socials of project/token:
Link to CoinMarketCap or CoinGecko page of project/token (if exists):

**Comment by yasha-black** [comment]
@WalrusDAO 
Added #19
