### ISSUE TITLE
$PROXIE ProxiesNFT

### ISSUE THREAD

**Issue by CyberiadaProxy** [spectrum-finance/default-token-list#25]
- [x] I understand that token listing is not required to use the ErgoDEX Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the ErgoDEX default token list.
- [x] I will not ping the ErgoDEX team about this listing request.

**Please provide the following information for your token.**

Network:  Ergo
Project Name: ProxiesNFT 
Link to explorer:  https://explorer.ergoplatform.com/en/token/01ddcc3d0205c2da8a067ffe047a2ccfc3e8241bc3fcc6f6ebc96b7f7363bb36
URI to token's logo:  [QmZn2uqqSG6CvJB2s3Qz22FrnfEqFVCMePb5m72ySxzgs6]
                                    https://gateway.pinata.cloud/ipfs/QmZn2uqqSG6CvJB2s3Qz22FrnfEqFVCMePb5m72ySxzgs6
Token Name:  $PROXIE
Token Decimals:  6

Link to the official homepage of project/token:  https://proxiesnft.io/
Links to the official socials of project/token:  https://twitter.com/Proxies_NFT , https://discord.gg/theproxies , https://www.instagram.com/proxiesnft/
Link to CoinMarketCap or CoinGecko page of project/token (if exists): No.

**Comment by CyberiadaProxy** [comment]
> a file on a cloud storage or server.

[QmZn2uqqSG6CvJB2s3Qz22FrnfEqFVCMePb5m72ySxzgs6](https://gateway.pinata.cloud/ipfs/QmZn2uqqSG6CvJB2s3Qz22FrnfEqFVCMePb5m72ySxzgs6)

Here it is, Thank you.

**Comment by yasha-black** [comment]
@CyberiadaProxy added #27
