### ISSUE TITLE
Add GreasyCex: GreasyCex

### ISSUE THREAD

**Issue by Hq3r** [spectrum-finance/default-token-list#29]
- [x] I understand that token listing is not required to use the ErgoDEX Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the ErgoDEX default token list.
- [x] I will not ping the ErgoDEX team about this listing request.

**Please provide the following information for your token.**

Network:  Ergo
Project Name:  GreasyCex
Link to explorer:  https://explorer.ergoplatform.com/en/token/d1d2ae2ac0456aa43550dd4fda45e4f866d523be9170d3a3e4cab43a83926334
URI to token's logo:  https://ergcube.com/uploads/posts/2023-04/gcel1-sp.png
Token Name:  GreasyCex
Token Decimals:  0

Link to the official homepage of project/token:  https://t.me/ERGtrading
Links to the official socials of project/token:  https://t.me/ERGtrading
Link to CoinMarketCap or CoinGecko page of project/token (if exists):

**Comment by yasha-black** [comment]
@Hq3r 
Could you please provide any evidence that the token will have liquidity?

**Comment by Hq3r** [comment]
https://app.spectrum.fi/ergo/liquidity/68ed2d3b33624409830d877c6e6d431615862eabdcd660ddf30eee1972f1f858 
GreasyCex token already has its Lp on spectrum with liquidity
