### ISSUE TITLE
Add $bass ErgBass token

### ISSUE THREAD

**Issue by Awashbu12** [spectrum-finance/default-token-list#31]
- [X] I understand that token listing is not required to use the Spectrum Finance Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Spectrum Finance default token list.
- [X] I will not ping the Spectrum Finance team about this listing request.

**Please provide the following information for your token.**

Network:  Ergo
Project Name:  $Bass Token
Link to explorer:  https://explorer.ergoplatform.com/en/token/ba553573f83c61be880d79db0f4068177fa75ab7c250ce3543f7e7aeb471a9d2
URI to token's logo:  https://cloudflare-ipfs.com/ipfs/bafybeifjq7aaleq2eg4o4vhqsg2zjow6pkbb3upb7vpz6g24r777ikh5ua
Token Name:  $bass
Token Decimals:  7

Link to the official homepage of project/token:  https://ErgBass.xyz
Links to the official socials of project/token:  https://twitter.com/ErgBass
Link to CoinMarketCap or CoinGecko page of project/token (if exists): none

Initial liquidity (in base blockchain currency): currently has ERG: 171.399241501
$BASS: 511.6175672
Evidence of liquidity (provide any evidence that the token will have liquidity): 
Liquidity is on spectrum and locked for 100 years.

**Comment by yasha-black** [comment]
Added #32
