### ISSUE TITLE
Add ErgOne: ErgOne

### ISSUE THREAD

**Issue by koukarin** [spectrum-finance/default-token-list#33]
- [x] I understand that token listing is not required to use the Spectrum Finance Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Spectrum Finance default token list.
- [x] I will not ping the Spectrum Finance team about this listing request.

**Please provide the following information for your token.**

Network:  Ergo
Project Name:  ErgOne
Link to explorer:  https://explorer.ergoplatform.com/en/token/fcfca7654fb0da57ecf9a3f489bcbeb1d43b56dce7e73b352f7bc6f2561d2a1b
URI to token's logo:  https://ergone.io/img/background.png
Token Name:  ErgOne
Token Decimals:  8

Link to the official homepage of project/token:  https://ergone.io/
Links to the official socials of project/token:  
https://twitter.com/Erg0ne
https://t.me/Erg0ne

Link to CoinMarketCap or CoinGecko page of project/token (if exists): 

Initial liquidity (in base blockchain currency):  100000000000000
Evidence of liquidity (provide any evidence that the token will have liquidity): 
https://app.spectrum.fi/ergo/liquidity/94e7c5993db6bf42ec4473379f12194edab6eb0e858b3c256efd69fd786ef72a

**Comment by yasha-black** [comment]
@koukarin this repo was archived
added in https://github.com/spectrum-finance/ergo-token-list/pull/2
